### ISSUE TITLE
seems at every image instance the camera can see all the 3d points

### ISSUE THREAD

**Issue by chenchr** [HeYijia/vio_data_simulation#1]
Hello. I run the code and browse the keyframe directory, in every all_points_xxx.txt, there are 36 points, the same as the number of point generated.

**Comment by HeYijia** [comment]
Yes, actually，the house model should only have 18 points. However, I double it by transforming the 18 points to another coordinate. If you look the demo picture carefully, you will understand it. Maybe you just want a house model (18 points, not 36 points), you can just read the 18 lines in front of the all_points_xxx.txt.  good luck.

**Comment by HeYijia** [comment]
Hum, yes, every camera frame can see all the 3d points. I do not limit the image size. Only if the Z-axis of the 3d points in camera frame is negative, this point will not be observed.  So, the intrinsic parameter matrixes is an identity matrix.

**Comment by chenchr** [comment]
Thanks. In the paper  ```preintegration...``` by forster, he setup the 3d feature outside the trace of  camera therefore only part of them can be saw at one instance, which maybe easy for test of filter based vio.

**Comment by HeYijia** [comment]
I also create a simulation dataset just like forster's work. It's very easy to change this code to produce that data. If you just want to verify your algorithm, I think this code is enough.
