### ISSUE TITLE
motionModel中欧拉角的计算

### ISSUE THREAD

**Issue by jyzhong** [HeYijia/vio_data_simulation#13]
请问贺博：
`  double k_roll = 0.1;
    double k_pitch = 0.2;
    Eigen::Vector3d eulerAngles(k_roll * cos(t) , k_pitch * sin(t) , K*t ); `
，欧拉角怎么计算的，如何理解？

**Comment by HeYijia** [comment]
这里设定的是三个角度，随着时间余弦，正弦变化，模长是 0.1 rad ， 0.2 rad等。
